#!/bin/bash
git clone git://github.com/kriszyp/narwhal.git
cd narwhal/packages
git clone git://github.com/kriszyp/perstore.git
git clone git://github.com/kriszyp/pintura.git
git clone git://github.com/kriszyp/jack.git
git clone git://github.com/kriszyp/persevere.git
git clone git://github.com/kriszyp/jsgi-node.git
git clone git://github.com/kriszyp/commonjs-utils.git
git clone git://github.com/kriskowal/wiky.git
git clone git://github.com/kriskowal/narcissus.git
cd ../..