#!/bin/bash
rm -Rf docs
rm -Rf bin
rm -Rf engines
rm -Rf examples
rm -Rf lib
rm -Rf packages
rm -Rf tests
rm -Rf gem_bin
wget http://github.com/kriszyp/narwhal/tarball/master
gzip -d kriszyp*
tar -xvf kriszyp*
rm *.tar
mv kriszyp*/* .
rm -Rf kriszyp*
cd packages

wget http://github.com/kriszyp/perstore/tarball/master
gzip -d kriszyp*
tar -xvf kriszyp*
rm *.tar
mv kriszyp* perstore
rm -Rf kriszyp*

wget http://github.com/kriszyp/pintura/tarball/master
gzip -d kriszyp*
tar -xvf kriszyp*
rm *.tar
mv kriszyp* pintura
rm -Rf kriszyp*

wget http://github.com/kriszyp/jack/tarball/master
gzip -d kriszyp*
tar -xvf kriszyp*
rm *.tar
mv kriszyp* jack
rm -Rf kriszyp*

wget http://github.com/kriszyp/persevere/tarball/master
gzip -d kriszyp*
tar -xvf kriszyp*
rm *.tar
mv kriszyp* persevere
rm -Rf kriszyp*

wget http://github.com/kriszyp/jsgi-node/tarball/master
gzip -d kriszyp*
tar -xvf kriszyp*
rm *.tar
mv kriszyp* jsgi-node
rm -Rf kriszyp*

wget http://github.com/kriszyp/commonjs-utils/tarball/master
gzip -d kriszyp*
tar -xvf kriszyp*
rm *.tar
mv kriszyp* commonjs-utils
rm -Rf kriszyp*

wget http://github.com/kriskowal/wiky/tarball/master
gzip -d kriskowal*
tar -xvf kriskowal*
rm *.tar
mv kriskowal* wiky
rm -Rf kriskowal*

wget http://github.com/kriskowal/narcissus/tarball/master
gzip -d kriskowal*
tar -xvf kriskowal*
rm *.tar
mv kriskowal* narcissus
rm -Rf kriskowal*

